// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GMM7q3PuTolICrJ-WdNume1Ni9hUC9U',
    appId: '1:702456398518:web:dbad83ee3c9640863e5c17',
    messagingSenderId: '702456398518',
    projectId: 'rates-e5ec7',
    authDomain: 'rates-e5ec7.firebaseapp.com',
    databaseURL: 'https://rates-e5ec7-default-rtdb.firebaseio.com',
    storageBucket: 'rates-e5ec7.appspot.com',
    measurementId: 'G-RD43TLBYDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ZpP1drsBEyNv1R_1ndx7ReACuhlbS9M',
    appId: '1:702456398518:android:35dd2e7c28aac9e13e5c17',
    messagingSenderId: '702456398518',
    projectId: 'rates-e5ec7',
    databaseURL: 'https://rates-e5ec7-default-rtdb.firebaseio.com',
    storageBucket: 'rates-e5ec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuwRmGLCgetzPA1c1ao1Tfpu3klXVpFTY',
    appId: '1:702456398518:ios:878c659094cf36953e5c17',
    messagingSenderId: '702456398518',
    projectId: 'rates-e5ec7',
    databaseURL: 'https://rates-e5ec7-default-rtdb.firebaseio.com',
    storageBucket: 'rates-e5ec7.appspot.com',
    iosClientId: '702456398518-kq7fiod97fj6tkdnonvmu8mhljo5b590.apps.googleusercontent.com',
    iosBundleId: 'com.example.shippingRates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuwRmGLCgetzPA1c1ao1Tfpu3klXVpFTY',
    appId: '1:702456398518:ios:878c659094cf36953e5c17',
    messagingSenderId: '702456398518',
    projectId: 'rates-e5ec7',
    databaseURL: 'https://rates-e5ec7-default-rtdb.firebaseio.com',
    storageBucket: 'rates-e5ec7.appspot.com',
    iosClientId: '702456398518-kq7fiod97fj6tkdnonvmu8mhljo5b590.apps.googleusercontent.com',
    iosBundleId: 'com.example.shippingRates',
  );
}
